### PR TITLE
Fix failing tests, add Travis configuration, Add Plone 5.0 and 5.1. Add zope.formlib dependency for Plone 5.x compatibility.

### PR DESCRIPTION
**Pull request by tisto**

### CODE REVIEW

**Comment by tisto** [comment]
@davidjb this PR is ready to review. The Plone 5.1 tests currently fail on Travis. Though, this is just because of a bug in Plone which will be fixed in Plone 5.1.4.

**Review by davidjb — APPROVED** [review]
Looks great, awesome work and many thanks.  Merge away whenever you're ready.

**Comment by tisto** [comment]
@davidjb I'd like to try c.shibboleth for a client installation (where we can not install source code packages). Is it possible to do another release? If you want I can take care of this as well (pypi username: timo).

**Comment by davidjb** [comment]
Access granted, thanks for breathing life into this project 🙂

**Pull request merged**
